sitkoru/Sitko.Core

src/Sitko.Core.App.Web/Razor/RazorExtensions.cs
src/Sitko.Core.App.Web/Razor/ViewToStringRendererService.cs
src/Sitko.Core.App.Web/Sitko.Core.App.Web.csproj
src/Sitko.Core.Email/EmailModule.cs
src/Sitko.Core.Email/FluentMailSender.cs
src/Sitko.Core.Email/Sitko.Core.Email.csproj

#27 move ViewToStringRendererService to Sitko.Core.App.Web

---

src/Sitko.Core.Repository.EntityFrameworkCore/EFRepository.cs
src/Sitko.Core.Repository/BaseRepository.cs
src/Sitko.Core.Repository/IRepository.cs
tests/Sitko.Core.Repository.Tests/EFTests.cs

#51 Just add refresh method to repository

refresh async added to repo

---

src/Sitko.Core.Storage.FileSystem/FileSystemStorage.cs
src/Sitko.Core.Storage.Proxy/ImageSharp/ImageSharpProvider.cs
src/Sitko.Core.Storage.Proxy/StaticFiles/StorageFileContext.cs
src/Sitko.Core.Storage.S3/S3Storage.cs
src/Sitko.Core.Storage/Cache/BaseStorageCache.cs
src/Sitko.Core.Storage/Cache/FileStorageCache.cs
src/Sitko.Core.Storage/Cache/IStorageCache.cs
src/Sitko.Core.Storage/Cache/InMemoryStorageCache.cs
src/Sitko.Core.Storage/FileDownloadResult.cs
src/Sitko.Core.Storage/IStorage.cs
src/Sitko.Core.Storage/Storage.cs
src/Sitko.Core.Storage/StorageItem.cs
src/Sitko.Core.Storage/StorageItemMetadata.cs
tests/Sitko.Core.Storage.Tests/BasicTests.cs

Add medata support to Storage module. Save filename and date by default

#74 storage metadata support

---

.github/workflows/main.yml

Fix ci steps names

---

src/Sitko.Core.Storage.FileSystem/FileSystemStorage.cs
src/Sitko.Core.Storage.S3/IS3StorageOptions.cs
src/Sitko.Core.Storage.S3/S3Storage.cs
src/Sitko.Core.Storage/IStorage.cs
src/Sitko.Core.Storage/Storage.cs
src/Sitko.Core.Storage/StorageNode.cs
src/Sitko.Core.Storage/StorageOptions.cs
tests/Sitko.Core.Storage.S3.Tests/TestS3StorageSettings.cs

- Download metadata only if it present in all objects list
- Tree cache ttl is configurable
- Adding or deleting items refreshes the tree without reloading
- Path inside bucket for S3 is configurable

Improve storage tree build

---

apps/Sitko.Core.Apps.Blazor/Pages/Index.razor
apps/Sitko.Core.Apps.Blazor/Pages/Index.razor.cs
src/Sitko.Core.App.Blazor/Components/BaseComponent.cs
src/Sitko.Core.App.Blazor/Forms/BaseFormComponent.cs
src/Sitko.Core.Blazor.AntDesign/Components/AntForm.razor
src/Sitko.Core.Blazor.AntDesign/Components/AntRepositoryForm.razor
src/Sitko.Core.Blazor.AntDesign/Components/BaseAntListComponent.cs

1. New base component for Blazor
2. Initialization is guaranteed before render
3. More DI helper methods

Improved base component with forced initialization before render

---

src/Sitko.Core.Repository.EntityFrameworkCore/EFRepository.cs
src/Sitko.Core.Repository.EntityFrameworkCore/EFRepositoryContext.cs
src/Sitko.Core.Repository.EntityFrameworkCore/IsExternalInit.cs
src/Sitko.Core.Repository.EntityFrameworkCore/Sitko.Core.Repository.EntityFrameworkCore.csproj
src/Sitko.Core.Repository/BaseRepository.cs
src/Sitko.Core.Repository/IRepository.cs
src/Sitko.Core.Repository/Sitko.Core.Repository.csproj
src/Sitko.Core.Xunit/BaseTestScope.cs
src/Sitko.Core.Xunit/DbBaseTestScope.cs
src/Sitko.Core.Xunit/Sitko.Core.Xunit.csproj
tests/Sitko.Core.Repository.Tests/EFTests.cs

Smart update for disconnected entities

Implement external updates

---

src/Sitko.Core.Blazor.Wasm/WasmApplication.cs
src/Sitko.Core.Blazor.Wasm/WasmApplicationContext.cs

Final application must configure WebAssemblyHostBuilder and supply RootComponents

WASM App refactoring

---

src/Sitko.Core.App/Application.cs
src/Sitko.Core.App/HostedApplication.cs
src/Sitko.Core.App/Logging/LoggingExtensions.cs
src/Sitko.Core.Blazor.Server/BlazorApplication.cs
src/Sitko.Core.Blazor.Wasm/IWasmApplicationModule.cs
src/Sitko.Core.Blazor.Wasm/Sitko.Core.Blazor.Wasm.csproj
src/Sitko.Core.Blazor.Wasm/WasmApplication.cs
src/Sitko.Core.Blazor/Components/BaseStateComponent.cs
src/Sitko.Core.Blazor/Sitko.Core.Blazor.csproj

- Logging
- Configuration
- State persistence

Improve WASM support

---

src/Sitko.Core.Blazor.MudBlazor/Components/Layout/BasicMudLayout.razor

fix: added condition for displaying header container

---

apps/Sitko.Core.Apps.Blazor/Sitko.Core.Apps.Blazor.csproj
apps/Sitko.Core.Apps.MudBlazorDemo/Sitko.Core.Apps.MudBlazorDemo.csproj
apps/WASMDemo.Client/WASMDemo.Client.csproj
apps/WASMDemo.Shared/WASMDemo.Shared.csproj
perf/Sitko.Core.App.Perf/Sitko.Core.App.Perf.csproj
src/Directory.Packages.props
src/Sitko.Core.Health.Telegram/TelegramHealthCheckPublisher.cs
tests/Directory.Build.props
tests/Sitko.Core.Pdf.Tests/Sitko.Core.Pdf.Tests.csproj
tests/Sitko.Core.Storage.Metadata.Postgres.Tests/Sitko.Core.Storage.Metadata.Postgres.Tests.csproj

- .NET 6.0.21 and 7.0.10
- MudBlazor
- AntDesign
- MailKit
- Serilog
- Puppeteer
- gRPC
- Telegram.Bot

August 203 dependencies update

---

src/Sitko.Core.Repository.Grpc/RepositoryExtensions.cs

feat: added extension for apply request params to query

---

src/Sitko.Core.Storage.FileSystem/FileSystemStorageMetadataProvider.cs
src/Sitko.Core.Storage.Remote/RemoteStorageMetadataProvider.cs
src/Sitko.Core.Storage.S3/S3StorageMetadataProvider.cs
src/Sitko.Core.Storage/Metadata/EmbedStorageMetadataProvider.cs
src/Sitko.Core.Storage/StorageNode.cs
tests/Sitko.Core.Storage.Tests/BasicTests.cs

update local metadata cache in embed provider when metadata added/updated/deleted

Invalidate embed storage cache

---

src/Sitko.Core.Storage.S3/S3Storage.cs
src/Sitko.Core.Storage.S3/S3StorageModule.cs
src/Sitko.Core.Storage/Metadata/EmbedStorageMetadataProvider.cs
src/Sitko.Core.Storage/Storage.cs
tests/Sitko.Core.Storage.S3.Tests/BaseS3StorageTestScope.cs

Storage: Fix bucket traverse

---

src/Directory.Packages.props
src/Sitko.Core.Grpc.Client/GrpcClientModuleOptions.cs
src/Sitko.Core.Grpc.Client/IGrpcMetadataProvider.cs
src/Sitko.Core.Grpc.Server/BaseGrpcServerModule.cs
src/Sitko.Core.Grpc.Server/Discovery/DiscoveryGrpcServerModule.cs
src/Sitko.Core.Grpc.Server/GrpcServerModuleOptions.cs
src/Sitko.Core.Grpc.Server/IGrpcServerModule.cs
src/Sitko.Core.Grpc.Server/Sitko.Core.Grpc.Server.csproj

Allow to enable grpc-web for specific services

Add grpc-web support on server side

---

src/Directory.Packages.props
src/Sitko.Core.App/Logging/TraceMetaEnricher.cs
src/Sitko.Core.App/Sitko.Core.App.csproj
src/Sitko.Core.App/SitkoCoreBaseApplicationBuilder.cs
src/Sitko.Core.Tasks/Execution/BaseTaskExecutor.cs
src/Sitko.Core.Tasks/Execution/ITaskExecutorContext.cs
src/Sitko.Core.Tasks/Execution/TaskExecutorContext.cs
src/Sitko.Core.Tasks/Sitko.Core.Tasks.csproj
src/Sitko.Core.Tasks/Tracing/TracingHelper.cs

1. Send tracing data top opensearch
2. Use .net tracing in tasks

Tracing fixes

---

src/Sitko.Core.Search.OpenSearch/OpenSearchSearcher.cs

fix: fixed logs for OpenSearch

---

src/Sitko.Core.Search.ElasticSearch/ElasticSearcher.cs
src/Sitko.Core.Search.OpenSearch/OpenSearchSearcher.cs
src/Sitko.Core.Search/BaseSearchProvider.cs
src/Sitko.Core.Search/ISearchProvider.cs
src/Sitko.Core.Search/ISearcher.cs
src/Sitko.Core.Search/SearchType.cs
tests/Sitko.Core.Search.ElasticSearch.Tests/ElasticSearchTests.cs
tests/Sitko.Core.Search.OpenSearch.Tests/OpenSearchTests.cs

feat: added Wildcard searching

---

src/Sitko.Core.Search.OpenSearch/OpenSearchSearcher.cs
tests/Sitko.Core.Search.OpenSearch.Tests/OpenSearchTests.cs

feat: update searching by numbers

---

src/Sitko.Core.Repository.Search/BaseRepositorySearchProvider.cs
src/Sitko.Core.Search.ElasticSearch/ElasticSearcher.cs
src/Sitko.Core.Search.OpenSearch/OpenSearchModuleOptions.cs
src/Sitko.Core.Search.OpenSearch/OpenSearchSearcher.cs
src/Sitko.Core.Search/BaseSearchProvider.cs
src/Sitko.Core.Search/ISearchProvider.cs
src/Sitko.Core.Search/ISearcher.cs
src/Sitko.Core.Search/SearchModel.cs
src/Sitko.Core.Search/SearchModule.cs
src/Sitko.Core.Search/SearchResult.cs
tests/Sitko.Core.Search.ElasticSearch.Tests/ElasticSearchTests.cs
tests/Sitko.Core.Search.OpenSearch.Tests/OpenSearchTests.cs

feat: added Highlighting to opensearch

---

src/Sitko.Core.Search.OpenSearch/OpenSearchSearcher.cs
tests/Sitko.Core.Search.OpenSearch.Tests/OpenSearchTests.cs

fix: fixed HighlightingTestAsync with tags

---

src/Directory.Packages.props
src/Sitko.Core.Puppeteer/BrowserProvider.cs
src/Sitko.Core.Puppeteer/PuppeteerModuleOptions.cs

feat: updated PuppeteerSharp

---

src/Sitko.Core.Blazor.MudBlazor/Components/Table/MudTable.razor
src/Sitko.Core.Blazor.MudBlazor/Components/Table/MudTable.razor.cs

feat: аdd a group header template to the table

---

src/Sitko.Core.Blazor.MudBlazor/Components/Table/MudTable.razor
src/Sitko.Core.Blazor.MudBlazor/Components/Table/MudTable.razor.cs

feat: add GroupFooterTemplate

---

src/Sitko.Core.Auth.Basic/BasicAuthModuleOptions.cs
src/Sitko.Core.Auth.Google/GoogleAuthModuleOptions.cs
src/Sitko.Core.Auth.IdentityServer/JwtIdentityServerModuleOptions.cs
src/Sitko.Core.Auth.IdentityServer/OidcIdentityServerModuleOptions.cs
src/Sitko.Core.Auth/AuthModule.cs
src/Sitko.Core.Auth/AuthOptions.cs
src/Sitko.Core.Identity/IdentityModule.cs
src/Sitko.Core.Identity/Sitko.Core.Identity.csproj

- data protection
- authorization policy

Unify identity module with base auth module

---

.github/workflows/main.yml
src/Sitko.Core.Repository.Search/BaseRepositorySearchProvider.cs
src/Sitko.Core.Search.ElasticSearch/ElasticSearcher.cs
src/Sitko.Core.Search.OpenSearch/OpenSearchModuleOptions.cs
src/Sitko.Core.Search.OpenSearch/OpenSearchSearcher.cs
src/Sitko.Core.Search/BaseSearchProvider.cs
src/Sitko.Core.Search/ISearchProvider.cs
src/Sitko.Core.Search/ISearcher.cs
src/Sitko.Core.Search/SearchModel.cs
src/Sitko.Core.Search/SearchOptions.cs
src/Sitko.Core.Search/SearchResult.cs
src/Sitko.Core.Search/SearcherEntity.cs
tests/Sitko.Core.Search.ElasticSearch.Tests/ElasticSearchTests.cs
tests/Sitko.Core.Search.OpenSearch.Tests/OpenSearchTests.cs

Now we can add tags to search models and after use them to filter results

Tags in search
